# Generated by Django 4.1.5 on 2023-01-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile2.png', null=True, upload_to='images'),
        ),
    ]
