# Generated by Django 4.1.5 on 2023-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pupil_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=200, null=True)),
                ('option2', models.CharField(max_length=200, null=True)),
                ('yes', models.BooleanField(default=True)),
                ('no', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=200, null=True)),
                ('option2', models.CharField(max_length=200, null=True)),
                ('option3', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperamentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Экстраверсия - интроверсия', 'Экстраверсия - интроверсия'), ('Нейротизм', 'Нейротизм'), ('Шкала лжи', 'Шкала лжи')], max_length=100)),
                ('key', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('time', models.IntegerField()),
                ('url', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
