# Generated by Django 4.1.5 on 2023-01-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_criteria_overall'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PupilResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(null=True)),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pupil')),
                ('result_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inforesult')),
            ],
        ),
    ]
