# Generated by Django 4.1.5 on 2023-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_inforesult_pupilresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
