# Generated by Django 4.1.5 on 2023-01-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_pupil_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='fio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
